# Generated by Django 3.2.9 on 2021-11-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_listing_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllisting',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
